#ifndef _ERROR_H
#define _ERROR_H

#define NOT_VALID_INSTRUCTION 45
#define NOT_VALID_OPERAND 46
#define EXTRA_OPERAND 47
#define NOT_VALID_OPERATOR 48
#define NOT_VALID_IDENTIFIER 49

#endif // _ERROR_H
